jobs:
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - bash: |
      set -e
      curl -LO https://github.com/bazelbuild/bazel/releases/download/0.23.2/bazel-0.23.2-windows-x86_64.exe
      mv bazel-*.exe bazel.exe
      mkdir /c/bazel
      mv bazel.exe /c/bazel
      /c/bazel/bazel.exe info release

    displayName: 'Install Bazel'

  - powershell: |
        Write-Host "Enable long path behavior"
        # See https://docs.microsoft.com/en-us/windows/desktop/fileio/naming-a-file#maximum-path-length-limitation
        Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1
    displayName: "Enable da long paths"

  - bash: |
      set -e
      export MSYS2_ARG_CONV_EXCL="*"

      /c/bazel/bazel.exe build --config windows \
        "@haskell_aeson//..." \
        "@haskell_aeson__extra//..." \
        "@haskell_cassava//..." \
        "@haskell_conduit//..." \
        "@haskell_fuzzyset//..." \
        "@haskell_lens//..." \
        "@haskell_text__metrics//..."

      # FIXME:
      # this rule is missing dependency declarations for the following files included by 'external/haskell_zlib/cbits/adler32.c':
      #   'external/haskell_zlib/cbits/zutil.h'
      #   'external/haskell_zlib/cbits/zlib.h'
      #   'external/haskell_zlib/cbits/zconf.h'
      #/c/bazel/bazel.exe build --config windows "@haskell_zlib//..."

      # FIXME: needs network, warp, cryptonite, etc...
      # /c/bazel/bazel.exe build --config windows "@haskell_wai__app__static//..."

      # FIXME: Needs to provide advapi32 extra lib.
      # /c/bazel/bazel.exe build --config windows "@haskell_entropy//..."

      # FIXME: no such package '@taglib//': Platform is not supported (see 'fail_not_supported') and referenced by '@haskell_htaglib//:htaglib'
      # /c/bazel/bazel.exe build --config windows "@haskell_htaglib//..."

      # FIXME: Cabal version macros issue
      # /c/bazel/bazel.exe build --config windows "@haskell_pretty__show//..."

      # FIXME: need custom builds
      # /c/bazel/bazel.exe build --config windows "@haskell_network_1843485230//..."
      # /c/bazel/bazel.exe build --config windows "@haskell_postgresql_libpq_275795853//..."

      # FIXME: depends on network
      # /c/bazel/bazel.exe build --config windows "@haskell_http__client//..."

    displayName: 'Hazel Tests'

  - bash: |
      set -e
      export MSYS2_ARG_CONV_EXCL="*"
      # Tests that build but don't run
      /c/bazel/bazel.exe build --config windows \
        "//tests/c-compiles-still/..." \
        "//tests/binary-with-data/..." \
        "//tests/binary-indirect-cbits"

      # Tests that only require building
      # (when using 'test' CI fails with:
      #     ERROR: No test targets were found, yet testing was requested
      # )
      # See https://github.com/bazelbuild/bazel/issues/7291
      /c/bazel/bazel.exe build --config windows \
        "//tests/data/..." \
        "//tests/failures/..." \
        "//tests/hidden-modules/..." \
        "//tests/package-id-clash/..." \

      # Tests that succeed
      /c/bazel/bazel.exe test --config windows \
        "//tests:test-binary-simple" \
        "//tests:test-binary-custom-main" \
        "//tests/binary-custom-main/..." \
        "//tests/binary-exe-path/..." \
        "//tests/binary-with-data/..." \
        "//tests/binary-with-lib/..." \
        "//tests/binary-with-main/..." \
        "//tests/binary-simple/..." \
        "//tests/binary-with-compiler-flags/..." \
        "//tests/binary-with-import/..." \
        "//tests/binary-with-link-flags/..." \
        "//tests/cpp_macro_conflict/..." \
        "//tests/extra-source-files/..." \
        "//tests/java_classpath/..." \
        "//tests/generated-modules/..." \
        "//tests/haskell_lint/..." \
        "//tests/haskell_test/..." \
        "//tests/hs-boot/..." \
        "//tests/indirect-link/..." \
        "//tests/library-deps/..." \
        "//tests/library-exports/..." \
        "//tests/library-linkstatic-flag/..." \
        "//tests/lhs/..." \
        "//tests/package-id-clash-binary/..." \
        "//tests/package-name/..." \
        "//tests/textual-hdrs/..." \
        "//tests/two-libs/..." \
        "//tests/encoding/..." \
        "//tests/c-compiles/..."

    displayName: 'Run Bazel'
